language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install -r test_margarine/requirements.txt"
script:
  - python setup.py install
  - nosetests
notifications:
  irc: 'chat.freenode.net#margarine'
