language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r test_margarine/requirements.txt --use-mirrors"
script: python -m test_margarine
notifications:
  email:
    recipients:
      - margarine-dev@googlegroups.com
  irc: 'chat.freenode.net#margarine'
