language: python
python:
  - 2.7
matrix:
  fast_finish: true
install:
  - mv setup.cfg{,.bak}
  - pip install -q -r requirements.txt
  - pip install -q -r test_margarine/requirements.txt
  - pip install -q flake8
  - mv setup.cfg{.bak,}
script:
  - pip install .
  - flake8
  - nosetests
notifications:
  irc: chat.freenode.net#margarine
